### ISSUE TITLE
install for win10

### ISSUE THREAD

**Issue by Harry825** [125K/WiFi-Spam#7]
How do you go about installing for Windows 10?

**Comment by trigger337** [comment]
you can't

**Comment by HuskyCodez** [comment]
> How do you go about installing for Windows 10?

you could try to use WSL

**Comment by trigger337** [comment]
WSL is less functional. Keep in mind that you CAN install it on WSL, but it might NOT work.

**Comment by 125K** [comment]
@Harry825 just run it on a Virtual Machine with Linux installed
